# fly.toml file generated for my-chatgpt-bot on 2023-03-13T21:57:28+08:00

app = "my-chatgpt-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"

[build]
  [build.args]
    MONGODB_PATH = "/data/db"
    MONGODB_PORT = "27017"
    env-file = "config/config.env"
