# fly.toml file generated for chatgpt-bot-mongo-express on 2023-03-14T12:04:11+08:00

app = "chatgpt-bot-mongo-express"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 3
    timeout = "3s"
